[project]
name = "pandas-exercises"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
    "pandas>=2.3.2",
    "pandas-datareader>=0.10.0",
    "seaborn>=0.13.2",
]
